# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'HW4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HW4
  pod 'IQKeyboardManagerSwift'

  target 'HW4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HW4UITests' do
    # Pods for testing
  end

end
